### ISSUE TITLE
NativeAOT-LLVM: Wasi tracking

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2269]
This PR is to track issues that are known to be problems with the wasi-wasm RID.

- [ ] System.Globalization (solve by building ICU for wasi-sdk presumably)  
- [ ] thread stack size, `PalGetMaximumStackBounds` / `pthread_attr_get`
- [ ] mmap/munmap - need to track the blocks ourselves, in a double linked list might be enough initially, even if prone to fragmentation and sub optimal performance
- [x] Build integration - WIP in https://github.com/dotnet/runtimelab/pull/2268

**Comment by mhmd-azeez** [comment]
Hi, do you have a small sample for `wasi-wasm`? I have trouble building it:

```csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.ILCompiler.LLVM" Version="9.0.0-dev" />
    <PackageReference Include="runtime.win-x64.Microsoft.DotNet.ILCompiler.LLVM" Version="9.0.0-dev" />
    <PackageReference Include="runtime.browser-wasm.Microsoft.DotNet.ILCompiler.LLVM" Version="9.0.0-dev" />
    <PackageReference Include="runtime.wasi-wasm.Microsoft.DotNet.ILCompiler.LLVM" Version="9.0.0-dev" />
  </ItemGroup>
</Project>
```

```
PS D:\x\dotnet\aotwasm> dotnet publish -r wasi-wasm /p:TargetArchitecture=wasm /p:PlatformTarget=AnyCPU /p:MSBuildEnableWorkloadResolver=false --self-contained            
MSBuild version 17.8.0+6cdef4241 for .NET
  Determining projects to restore...
C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(1
48,5): error NETSDK1084: There is no application host available for the specified RuntimeIdentifier 'wasi-wasm'. [D:\x\dotnet\aotwasm\ao 
twasm.csproj]
C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(1 
48,5): error NETSDK1084: There is no application host available for the specified RuntimeIdentifier 'wasi-wasm'. [D:\x\dotnet\aotwasm\ao 
twasm.csproj]
C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(1 
48,5): error NETSDK1084: There is no application host available for the specified RuntimeIdentifier 'wasi-wasm'. [D:\x\dotnet\aotwasm\ao 
twasm.csproj]
C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(1 
48,5): error NETSDK1084: There is no application host available for the specified RuntimeIdentifier 'wasi-wasm'. [D:\x\dotnet\aotwasm\ao 
twasm.csproj]
```

Same thing works for `browser-wasm`:
```
PS D:\x\dotnet\aotwasm> dotnet publish -r browser-wasm /p:TargetArchitecture=wasm /p:PlatformTarget=AnyCPU /p:MSBuildEnableWorkloadResolver=false --self-contained
MSBuild version 17.8.0+6cdef4241 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(311,5):
 message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [D:\x\dotnet\aotwasm\aotwasm.csp 
roj]
  aotwasm -> D:\x\dotnet\aotwasm\bin\Release\net8.0\browser-wasm\aotwasm.dll
C:\Users\muham\.nuget\packages\microsoft.dotnet.ilcompiler.llvm\9.0.0-dev\build\Microsoft.NETCore.Native.Publish.targets(48,5): warning 
: The published project has a runtimeconfig.template.json that is not supported by PublishAot. Move the configuration to the project fil 
e using RuntimeHostConfigurationOption. [D:\x\dotnet\aotwasm\aotwasm.csproj]
  Generating native code
  ILC: Method '[S.P.CoreLib]Interop+JsGlobalization.StartsWith(string&,char*,int32,char*,int32,CompareOptions,int32&,object&)' will alwa
  ys throw because: Invalid IL or CLR metadata in 'Boolean JsGlobalization.StartsWith(System.String ByRef, Char*, Int32, Char*, Int32, S 
  ystem.Globalization.CompareOptions, Int32 ByRef, System.Object ByRef)'
  ILC: Method '[S.P.CoreLib]Interop+JsGlobalization.GetCultureInfo(string&,char*,int32,int32&,object&)' will always throw because: Inval
  id IL or CLR metadata in 'Int32 JsGlobalization.GetCultureInfo(System.String ByRef, Char*, Int32, Int32 ByRef, System.Object ByRef)'   
  ILC: Method '[S.P.CoreLib]Interop+JsGlobalization.GetFirstDayOfWeek(string&,int32&,object&)' will always throw because: Invalid IL or 
  CLR metadata in 'Int32 JsGlobalization.GetFirstDayOfWeek(System.String ByRef, Int32 ByRef, System.Object ByRef)'
  ILC: Method '[S.P.CoreLib]Interop+JsGlobalization.GetFirstWeekOfYear(string&,int32&,object&)' will always throw because: Invalid IL or
   CLR metadata in 'Int32 JsGlobalization.GetFirstWeekOfYear(System.String ByRef, Int32 ByRef, System.Object ByRef)'
  ILC: Method '[S.P.CoreLib]Interop+JsGlobalization.CompareString(string&,char*,int32,char*,int32,CompareOptions,int32&,object&)' will a
  lways throw because: Invalid IL or CLR metadata in 'Int32 JsGlobalization.CompareString(System.String ByRef, Char*, Int32, Char*, Int3 
  2, System.Globalization.CompareOptions, Int32 ByRef, System.Object ByRef)'
  ILC: Method '[S.P.CoreLib]Interop+JsGlobalization.ChangeCaseInvariant(char*,int32,char*,int32,bool,int32&,object&)' will always throw 
  because: Invalid IL or CLR metadata in 'Void JsGlobalization.ChangeCaseInvariant(Char*, Int32, Char*, Int32, Boolean, Int32 ByRef, Sys 
  tem.Object ByRef)'
  ILC: Method '[S.P.CoreLib]Interop+JsGlobalization.ChangeCase(string&,char*,int32,char*,int32,bool,int32&,object&)' will always throw b 
  ecause: Invalid IL or CLR metadata in 'Void JsGlobalization.ChangeCase(System.String ByRef, Char*, Int32, Char*, Int32, Boolean, Int32 
   ByRef, System.Object ByRef)'
  ILC: Method '[S.P.CoreLib]Interop+JsGlobalization.EndsWith(string&,char*,int32,char*,int32,CompareOptions,int32&,object&)' will always
   throw because: Invalid IL or CLR metadata in 'Boolean JsGlobalization.EndsWith(System.String ByRef, Char*, Int32, Char*, Int32, Syste 
  m.Globalization.CompareOptions, Int32 ByRef, System.Object ByRef)'
  ILC: Method '[S.P.CoreLib]Interop+JsGlobalization.GetCalendarInfo(string&,CalendarId,char*,int32,int32&,object&)' will always throw be
  cause: Invalid IL or CLR metadata in 'Int32 JsGlobalization.GetCalendarInfo(System.String ByRef, System.Globalization.CalendarId, Char 
  *, Int32, Int32 ByRef, System.Object ByRef)'
  ILC: Method '[S.P.CoreLib]Interop+JsGlobalization.IndexOf(string&,char*,int32,char*,int32,CompareOptions,bool,int32&,object&)' will al
  ways throw because: Invalid IL or CLR metadata in 'Int32 JsGlobalization.IndexOf(System.String ByRef, Char*, Int32, Char*, Int32, Syst 
  em.Globalization.CompareOptions, Boolean, Int32 ByRef, System.Object ByRef)'
  LLVM compilation to IR finished in 6.77 seconds
  LLVM generation of bitcode finished in 14.47 seconds
EXEC : warning : undefined symbol: NativeRuntimeEventSource_LogExceptionThrown (referenced by top-level compiled C/C++ code) [D:\x\dotne
t\aotwasm\aotwasm.csproj]
emcc : warning : warnings in JS library compilation [-Wjs-compiler] [D:\x\dotnet\aotwasm\aotwasm.csproj]
  aotwasm -> D:\x\dotnet\aotwasm\bin\Release\net8.0\browser-wasm\publish\
```

Any idea what I am missing?

**Comment by yowl** [comment]
Can you try to add `/p:UseAppHost=false` to the wasi command line?

**Comment by mhmd-azeez** [comment]
@yowl thank you very much, it works!

```
PS D:\x\dotnet\aotwasm> dotnet publish -r wasi-wasm /p:TargetArchitecture=wasm /p:PlatformTarget=AnyCPU /p:MSBuildEnableWorkloadResolver=false --self-contained /p:UseAppHost=false
MSBuild version 17.8.0+6cdef4241 for .NET
  Determining projects to restore...
  Restored D:\x\dotnet\aotwasm\aotwasm.csproj (in 1.01 sec).
C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInferenc
e.targets(311,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-polic
y [D:\x\dotnet\aotwasm\aotwasm.csproj]
  aotwasm -> D:\x\dotnet\aotwasm\bin\Release\net8.0\wasi-wasm\aotwasm.dll
C:\Users\muham\.nuget\packages\microsoft.dotnet.ilcompiler.llvm\9.0.0-dev\build\Microsoft.NETCore.Native.Publish.target
s(48,5): warning : The published project has a runtimeconfig.template.json that is not supported by PublishAot. Move th
e configuration to the project file using RuntimeHostConfigurationOption. [D:\x\dotnet\aotwasm\aotwasm.csproj]
  Generating native code
  LLVM compilation to IR finished in 7.22 seconds
  LLVM generation of bitcode finished in 16.44 seconds
  aotwasm -> D:\x\dotnet\aotwasm\bin\Release\net8.0\wasi-wasm\publish\
PS D:\x\dotnet\aotwasm> explorer D:\x\dotnet\aotwasm\bin\Release\net8.0\wasi-wasm\publish\
PS D:\x\dotnet\aotwasm> wasm-objdump --details --section=import D:\x\dotnet\aotwasm\bin\Release\net8.0\wasi-wasm\publish\aotwasm.wasm

aotwasm.wasm:   file format wasm 0x1

Section Details:

Import[26]:
 - func[0] sig=8 <__imported_wasi_snapshot_preview1_args_get> <- wasi_snapshot_preview1.args_get
 - func[1] sig=8 <__imported_wasi_snapshot_preview1_args_sizes_get> <- wasi_snapshot_preview1.args_sizes_get
 - func[2] sig=8 <__imported_wasi_snapshot_preview1_environ_get> <- wasi_snapshot_preview1.environ_get
 - func[3] sig=8 <__imported_wasi_snapshot_preview1_environ_sizes_get> <- wasi_snapshot_preview1.environ_sizes_get
 - func[4] sig=40 <__imported_wasi_snapshot_preview1_clock_time_get> <- wasi_snapshot_preview1.clock_time_get
 - func[5] sig=32 <__imported_wasi_snapshot_preview1_fd_advise> <- wasi_snapshot_preview1.fd_advise
 - func[6] sig=5 <__imported_wasi_snapshot_preview1_fd_close> <- wasi_snapshot_preview1.fd_close
 - func[7] sig=8 <__imported_wasi_snapshot_preview1_fd_fdstat_get> <- wasi_snapshot_preview1.fd_fdstat_get
 - func[8] sig=8 <__imported_wasi_snapshot_preview1_fd_fdstat_set_flags> <- wasi_snapshot_preview1.fd_fdstat_set_flags
 - func[9] sig=8 <__imported_wasi_snapshot_preview1_fd_filestat_get> <- wasi_snapshot_preview1.fd_filestat_get
 - func[10] sig=30 <__imported_wasi_snapshot_preview1_fd_filestat_set_size> <- wasi_snapshot_preview1.fd_filestat_set_size
 - func[11] sig=64 <__imported_wasi_snapshot_preview1_fd_pread> <- wasi_snapshot_preview1.fd_pread
 - func[12] sig=8 <__imported_wasi_snapshot_preview1_fd_prestat_get> <- wasi_snapshot_preview1.fd_prestat_get
 - func[13] sig=1 <__imported_wasi_snapshot_preview1_fd_prestat_dir_name> <- wasi_snapshot_preview1.fd_prestat_dir_name
 - func[14] sig=6 <__imported_wasi_snapshot_preview1_fd_read> <- wasi_snapshot_preview1.fd_read
 - func[15] sig=64 <__imported_wasi_snapshot_preview1_fd_readdir> <- wasi_snapshot_preview1.fd_readdir
 - func[16] sig=53 <__imported_wasi_snapshot_preview1_fd_seek> <- wasi_snapshot_preview1.fd_seek
 - func[17] sig=6 <__imported_wasi_snapshot_preview1_fd_write> <- wasi_snapshot_preview1.fd_write
 - func[18] sig=0 <__imported_wasi_snapshot_preview1_path_filestat_get> <- wasi_snapshot_preview1.path_filestat_get
 - func[19] sig=65 <__imported_wasi_snapshot_preview1_path_open> <- wasi_snapshot_preview1.path_open
 - func[20] sig=17 <__imported_wasi_snapshot_preview1_path_readlink> <- wasi_snapshot_preview1.path_readlink
 - func[21] sig=1 <__imported_wasi_snapshot_preview1_path_unlink_file> <- wasi_snapshot_preview1.path_unlink_file
 - func[22] sig=6 <__imported_wasi_snapshot_preview1_poll_oneoff> <- wasi_snapshot_preview1.poll_oneoff
 - func[23] sig=4 <__imported_wasi_snapshot_preview1_proc_exit> <- wasi_snapshot_preview1.proc_exit
 - func[24] sig=11 <__imported_wasi_snapshot_preview1_sched_yield> <- wasi_snapshot_preview1.sched_yield
 - func[25] sig=8 <__imported_wasi_snapshot_preview1_random_get> <- wasi_snapshot_preview1.random_get
PS D:\x\dotnet\aotwasm> wasm-objdump --details --section=export D:\x\dotnet\aotwasm\bin\Release\net8.0\wasi-wasm\publish\aotwasm.wasm

aotwasm.wasm:   file format wasm 0x1

Section Details:

Export[2]:
 - memory[0] -> "memory"
 - func[33] <_start> -> "_start"
PS D:\x\dotnet\aotwasm> wasmtime run D:\x\dotnet\aotwasm\bin\Release\net8.0\wasi-wasm\publish\aotwasm.wasm
Hello, Wasi Console!
PS D:\x\dotnet\aotwasm>
```
