### ISSUE TITLE
[Projection tooling] Implement Demangler query methods

### ISSUE THREAD

**Issue by stephen-hawley** [dotnet/runtimelab#2665]
## Tasks

- [ ] Import a complete TypeSpec based signature for methods
- [ ] Given a type and protocol return the protocol witness table
- [x] Given a type and protocol return the conformance
- [ ] Given an async method return the async pointer
- [x] Given a type return the metadata accessor
- [ ] Given a func find the dispatch thunk for it
