### ISSUE TITLE
[Swift language features] Implement Swift enums in C#

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtimelab#2823]
## Tasks
 - [x] https://github.com/dotnet/runtimelab/issues/2881
 - [x] https://github.com/dotnet/runtimelab/issues/2836
 - [x] https://github.com/dotnet/runtimelab/issues/3029
 - [ ] Add Dynamo emitter for non-linear code generation
 - [ ] Project trivial Swift enum into C# struct/class
 - [ ] Project trivial Swift enum with methods into C# struct/class
  - [ ] Project homogeneous Swift enum into C# struct/class
  - [ ] Project heterogeneous Swift enum into C# struct/class
