### ISSUE TITLE
[Swift runtime features] Implement Swift metadata

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtimelab#2838]
## Tasks
 - [x] https://github.com/dotnet/runtimelab/issues/2807
 - [x] https://github.com/dotnet/runtimelab/pull/2877
 - [x] https://github.com/dotnet/runtimelab/issues/2861
