### ISSUE TITLE
[Projection tooling] Design projection tooling to be extensible and ensure it outputs only supported types

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtimelab#2843]
## Tasks
 - [x] https://github.com/dotnet/runtimelab/issues/2890
 - [x] https://github.com/dotnet/runtimelab/issues/2891
 - [x] #2955
 - [ ] Create design diagram/document for filtering handler
 - [ ] Create design diagram/document for intermediate representation
 - [ ] Create design diagram/document for marshalling handlers
 - [ ] Create design diagram/document for emitters

> [!NOTE]  
> This issue tracks progress and will be expanded with more details. If specific tasks for this issue are not clear, this means that the task is not well defined yet and needs attention.
