### ISSUE TITLE
[Projection tooling] Refactor projection tooling to be extensible and ensure it outputs only supported types

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtimelab#2845]
## Tasks

 - [x] https://github.com/dotnet/runtimelab/issues/2844
 - [x] https://github.com/dotnet/runtimelab/issues/2799
 - [ ] Refactor filtering handler
 - [ ] Refactor intermediate representation
 - [ ] Refactor marshalling handlers
 - [ ] Refactor emitters
 - [ ] Code improvements
   - [ ] Improve _protocolConformanceSymbols to use a switch statement for startup improvements
   - [ ] https://github.com/dotnet/runtimelab/issues/2868
   - [ ] Generate _payloadSize only when it is used to improve startup cost
   - [ ] Prefix private static fields with s_
   - [ ] https://github.com/dotnet/runtimelab/issues/2997
   - [ ] https://github.com/dotnet/runtimelab/issues/2802
   - [ ] https://github.com/dotnet/runtimelab/issues/2925
   - [ ] https://github.com/dotnet/runtimelab/issues/2803
   - [ ] https://github.com/dotnet/runtimelab/issues/2928
   - [ ] Reduce redundant fields in the decls and type records

> [!NOTE]  
> This issue tracks progress and will be expanded with more details. If specific tasks for this issue are not clear, this means that the task is not well defined yet and needs attention.
