### ISSUE TITLE
[Projection tooling] Projection tooling improvements

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtimelab#2846]
## Tasks
 - [ ] https://github.com/dotnet/runtimelab/issues/2855
 - [ ] https://github.com/dotnet/runtimelab/issues/2961
 - [ ] https://github.com/dotnet/runtimelab/issues/2962
 - [ ] https://github.com/dotnet/runtimelab/issues/2966
 - [ ] https://github.com/dotnet/runtimelab/issues/2973
 - [ ] https://github.com/dotnet/runtimelab/issues/2889
 - [ ] https://github.com/dotnet/runtimelab/issues/3037
 - [ ] https://github.com/dotnet/runtimelab/issues/3019
 - [ ] https://github.com/dotnet/runtimelab/issues/2935
 - [ ] https://github.com/dotnet/runtimelab/issues/2950
 - [ ] https://github.com/dotnet/runtimelab/issues/2892
 - [ ] https://github.com/dotnet/runtimelab/issues/2970
 - [ ] https://github.com/dotnet/runtimelab/issues/3022
 - [ ] https://github.com/dotnet/runtimelab/issues/2845
 - [ ] https://github.com/dotnet/runtimelab/issues/3046
 - [ ] https://github.com/dotnet/runtimelab/issues/2914
 - [ ] https://github.com/dotnet/runtimelab/issues/3073
 - [ ] https://github.com/dotnet/runtimelab/issues/3049
 - [ ] https://github.com/dotnet/runtimelab/issues/3048

> [!NOTE]  
> This issue tracks progress and will be expanded with more details. If specific tasks for this issue are not clear, this means that the task is not well defined yet and needs attention.
