### ISSUE TITLE
[Swift ABI compatibility] Implement correct memory handling in C# bindings

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtimelab#2851]
## Tasks
 - [x] https://github.com/dotnet/runtimelab/pull/3008
 - [x] https://github.com/dotnet/runtimelab/pull/3009
 - [x] #3020
 - [x] #3035
 - [x] #3036
 - [x] #2978
 - [x] https://github.com/dotnet/runtimelab/issues/2975
 - [x] https://github.com/dotnet/runtimelab/issues/2974
 - [x] https://github.com/dotnet/runtimelab/issues/3018
