### ISSUE TITLE
COM interop support

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtimelab#306]
The Native AOT compiler does not support COM interop today. Attempt to use COM interop leads to errors like:
```
Unhandled Exception: System.PlatformNotSupportedException: COM Interop is not supported on this platform.
   at Internal.Runtime.CompilerHelpers.InteropHelpers.ConvertManagedComInterfaceToNative(Object) + 0x42
```

The right way to add support for COM interop to Native AOT runtime is combination of:
- [ ] Implement [ComWrappers](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.comwrappers) in the Native AOT runtime.
    - [x] ~~Add [CoreCLR ComWrappers implementation](https://github.com/dotnet/runtime/tree/master/src/coreclr/interop) to Native AOT build.~~
    - [x] Implement CCW - `CreateComInterfaceForObject` set of APIs
    - [x] Implement RCW - `CreateObjectForComInstance` set of APIs
    - [x] `ComWrappers.RegisterForMarshalling` - needed to replace built-in interop
    - [ ] `ComWrappers.RegisterForTrackerSupport` - WinRT-specific lifetime management
- [x] Implement [IDynamicInterfaceCastable](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.idynamicinterfacecastable) in the Native AOT runtime. CoreRT had a similar experimental feature before that was reverted in https://github.com/dotnet/corert/commit/5383d46c02e2375e181ea95407843c487106a55e . This commit provides approximate blue print for what the implementation should look like.
- [ ] Implemented support for shared generics with `IDynamicInterfaceCastable` https://github.com/dotnet/runtime/issues/72909
- [ ] External tool that generates the required COM marshaling stubs. There are several design options for how this tool can work; or there can even be multiple variants of this tool. The key difference between the different options is the source of truth that the tool consumes.
    - [ ] Source of truth are COM interface definitions in C#. This option is best for making the existing libraries that use COM interop work (e.g. WinForms or Avalonia). Source generator that is extension of [DllImportGenerator](https://github.com/dotnet/runtimelab/tree/feature/DllImportGenerator) may be a good implementation strategy for this option.
    - [ ] Source of truth are COM interface definitions in IDL or TLB file. This option is best for creating new libraries that use COM interop. The tool for this case would be conceptually similar to [cswinrt](https://github.com/microsoft/CsWinRT) tool for WinRT. 

https://github.com/dotnet/corert/issues/4219 has more discussion on this topic.

**Comment by jkotas** [comment]
I am making this up for grabs in case anybody is interested to work on this. We will be happy to provide guidance about details. This is a large project.

**Comment by jkoritzinsky** [comment]
cc: @kekekeks if you want to extend the MicroCom IDL reader you started working on.

**Comment by wjk** [comment]
I had an idea on how to implement this. It involves a `ComWrappers` implementation and a sidecar assembly containing all of the VTables that is generated at publish time from reflection on the assemblies input to ILC. However, I have three issues:

1. ComWrappers is not yet implemented on NativeAOT, and I have no idea whatsoever about how to implement it.
2. How would I handle implementing interfaces that are not visible to the sidecar assembly? (Think [`FileOpenDialog.FileOpenDialogRCW`](https://github.com/dotnet/winforms/blob/3a2230726a8fc52c41086aa296e8c260bdc4a315/src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs#L199)). I can locate them by their full name, and the vtable classes are generated from reflection over the original, but unless I actually implement the original interface (not a copy), an InvalidCastException will inevitably result. .NET does not do duck typing.
3. There can be only one ComWrappers implementation per program. How would we deal with a program that uses both COM and CsWinRT? (Windows Forms apps distributed in MSIX packages are a good example of this situation.) Is there some way I can delegate calls for objects I don’t handle to CsWinRT’s `ComWrappers` implementation? And how do we stop CsWinRT from throwing an exception while trying to register their own version?

I would appreciate assistance with point 1, and guidance with points 2 and 3. (Also, the “CoreCLR COM Wrappers” link in the OP is dead. You may want to fix that.) Thanks!

**Comment by kekekeks** [comment]
@wjk 
FYI: we have a generator tool that creates bidirectional COM glue code from IDL-like language, generated code looks like this: https://gist.github.com/kekekeks/ead299514c4d21c26425a48747756fb7 (the source IDL is in the same gist)

**Comment by wjk** [comment]
@kekekeks Very cool! I’ll borrow use your generator code to emit the COM glue (under MIT). Thanks for the pointer!

In fact, come to think of it, an IDL-like file would probably be a better choice for NativeAOT COM interop than reflecting the assemblies at build time. We would just need to manually generate default IDL files for the COM usage in Windows Forms and WPF, and include them in the package with ILC. For developer-defined COM types, they would need to write the IDL themselves. I looked at the `avn.idl` file in Avalonia, and it looks just about right for my needs (I may extend it a bit). Thanks again!

**Comment by kekekeks** [comment]
I was planning to extract that code to a standalone roslyn generator. That way it should be possible to use C# interface definitions as the source too.

Will probably do that during the winter holidays.

**Comment by wjk** [comment]
Converting the tool to a roslyn generator is a bad idea, as some of the interfaces we need to handle are in libraries we do not control (and therefore cannot recompile with your generator). I praised the use of IDL precisely because it sidestepped this difficult issue.

**Comment by kekekeks** [comment]
>are in libraries we do not control

What exactly does that change? Interop bridges are registered separately, take another look at the generated code.

**Comment by wjk** [comment]
@kekekeks You are correct. Registration of wrappers do not reference the end-developer-visible interface definition they wrap; it is done purely via GUID. This means that a Roslyn analyzer would be a perfectly viable way to go, as long as we can point it at an already-compiled DLL and have it create wrappers for its contents as well. (I am thinking specifically of Windows Forms and WPF, which both use COM internally. One of my design goals here is to not require the recompilation of those assemblies from source. It’s certainly possible, but _very_ inconvenient.)

**Comment by jkotas** [comment]
> ComWrappers is not yet implemented on NativeAOT, and I have no idea whatsoever about how to implement it.

I have added more granularity above. If you only need COM interop (e.g. for WinForms), you can ignore the special WinRT lifetime management.

> guidance with points 2

`IDynamicInterfaceCastable` depends of default interface method implementations that @MichalStrehovsky has been working on on and off. It can be tacked independently from 1. dotnet/corert@5383d46 should provide good set of hits what needs to be modified to make it work.

> How would I handle implementing interfaces that are not visible to the sidecar assembly?

This is a common pain point for source generators, discussed in https://github.com/dotnet/roslyn/issues/11149. There workarounds, but none of them is pretty:
- Use IL rewriting to inject "InternalsVisibleTo" into assemblies that Roslyn references
- Generate dummy stubs for the interfaces that needs referencing, and then post-process the result to IL-rewrite them away.
- Hack Roslyn internals. Roslyn has an internal option that does it, it is just not exposed via public interface.

> There can be only one ComWrappers implementation per program.

There can be more than one instance of ComWrappers alive in the process. The ComWrappers API is designed to allow libraries to carry their own local implementation of COM interop marshallers as internal implementation detail. 

The WPF shipping in .NET 5 is doing something similar for WinRT interop. There are a few internal implementation details in WPF that need WinRT interop, but we do not want to WPF to depend on the whole CsWinRT. The solution for that is "embedded" CsWinRT. We have internal instance of ComWrappers in WPF that handles the WinRT interop for the set of WinRT interfaces needed by WPF. WPF does not need the special WinRT lifetime management, so a local ComWrappers instance works for it just fine.

There can be only one instance of ComWrappers registered for:
- The special WinRT lifetime management
- The legacy marshalling (e.g. what `Marshal.GetComInterfaceForObject` calls)

Notice that these two global registrations are independent, so the global WinRT lifetime registration does not prohibit you from registering your side-car assembly.

**Comment by kekekeks** [comment]
>Use IL rewriting to inject "InternalsVisibleTo" into assemblies that Roslyn references

Is IgnoresAccessChecksTo supported by NativeAOT? There is also a [generator tool](https://github.com/aelij/IgnoresAccessChecksToGenerator) for creating dummy assemblies for Roslyn.

**Comment by jkotas** [comment]
> Is IgnoresAccessChecksTo supported by NativeAOT? 

Yes, it is.

**Comment by kant2002** [comment]
@jkotas is it possible that my previous PR for CoreRT tick at least some ticks?
Should `Add CoreCLR ComWrappers implementation` use c++ implementation, or I can play with C#. Is moving CoreRT PR is right way to start this task?

**Comment by jkotas** [comment]
> Add CoreCLR ComWrappers implementation use c++ implementation, or I can play with C#. 

You can make it work either way. I think using the C++ implementation will be less new code, but it may be uphill battle to get it to build and the result will be less pretty than C# implementation.

Yep, moving over the work you have done against CoreRT repo is a good way to start.

Thank you!

**Comment by kant2002** [comment]
During previous discussion, I was pointed by @jkoritzinsky  to https://github.com/microsoft/CsWinRT/blob/master/src/WinRT.Runtime/ComWrappersSupport.netstandard2.0.cs implementation which is change place from that time. I post link here, so I or anybody else who would like to pursue COM support will have this link around place where actual work happens.

**Comment by kant2002** [comment]
@jkotas can you please update what's currently implemented? If something require additional work, it would be good to know about that also in such actionable list of items.

**Comment by jkotas** [comment]
done

**Comment by kant2002** [comment]
WinForms require at least dotnet/runtimelab#167 to be implemented, without that UpDown control crashes. Also dotnet/runtimelab#972 for property grid and pictures

**Comment by kant2002** [comment]
@jkotas what should be done for `ComWrappers.RegisterForTrackerSupport - WinRT-specific lifetime management` item? I maybe not work on that immidiately, but at least I can take a look how interesting that would be to implement.

**Comment by jkotas** [comment]
> ComWrappers.RegisterForTrackerSupport

It would require querying for `IReferenceTracker` interfaces and implementing `IReferenceTrackerTarget` interfaces for objects that ask for the tracking support, and then use these interfaces during GC.

Note that the tracking is only required to avoid memory leaks in Xaml apps. The Xaml apps should be functional without it, except that they will be leaking memory. So it may be more interesting to make a simple CsWinRT applications work first. Only once they become functional enough to visibly leak memory, go back and implement this tracking.

**Comment by kant2002** [comment]
Thanks for explanation. Sounds like a plan.

**Comment by reflectronic** [comment]
> It would require querying for `IReferenceTracker` interfaces and implementing `IReferenceTrackerTarget` interfaces for objects that ask for the tracking support

Is it possible to share design docs for the reference tracking system? There is no documentation other than the very basic stuff at https://docs.microsoft.com/en-us/windows/win32/api/windows.ui.xaml.hosting.referencetracker/, and it is almost impossible to figure out the flow without staring endlessly at the CLR source code.

**Comment by kant2002** [comment]
I have now following errors

![image](https://user-images.githubusercontent.com/4257079/117292758-62bddb80-ae92-11eb-84b6-e1476fb9159f.png)
and 
![image](https://user-images.githubusercontent.com/4257079/117292834-75d0ab80-ae92-11eb-9f01-40257a3ac858.png)
and
![image](https://user-images.githubusercontent.com/4257079/117292993-ad3f5800-ae92-11eb-88cb-236534519b23.png)

First one stop buttons from working.

But form appears.

**Comment by wjk** [comment]
@kant2002 That’s actually been the status quo for some time now. Forms will load, 100% custom controls will draw and interact properly, but anything standard will crash due to the accessibility code in Windows Forms (which uses COM).

**Comment by kant2002** [comment]
@wjk Status quo is no more. Any issues which are in COM support can be counted as bugs in my opinion, but in general a lot things with COM will works. What I post is specifically to limitations of current ComWrappers implementation.
- [x] Marshal `object` as IUnknown. See dotnet/runtimelab#1089
- [x] `PreserveSig = false` which return non-void results. See dotnet/runtimelab#1206
- [x] `CoClass` support is non-existing. Which means that File dialogs would not work without some efforts from WinForms repo. See https://github.com/dotnet/winforms/pull/4971

That's only things which I know so far. 
Technically somebody can start play with WPF + ComWrappers and test how it's going. Maybe that would be less problematic.

**Comment by jkotas** [comment]
@kant2002 What are you using to provide the ComWrappers required by WinForms? Is it all hand-written or auto-generated?

>  File dialogs would not work without some efforts from WinForms repo.

This can be fixed by replacing `new FileOpenDialogRCW()` / `new FileSaveDialogRCW()` by a call to `Ole32.CoCreateInstance`. WinForms is actually doing that in other places, for example in StringSource.cs.

**Comment by hez2010** [comment]
@kant2002 
> Technically somebody can start play with WPF + ComWrappers and test how it's going. Maybe that would be less problematic.

WPF is using C++/CLI to inject code for module setup AFAIK. Unless they use module initializer to rewrite those code, I don't think WPF will work even with COM Wrapper implemented.

**Comment by jkotas** [comment]
WPF is using C++/CLI for more than that. The module initializer issue is a small problem. The overall WPF dependency on C++/CLI is the big problem.

**Comment by kant2002** [comment]
For now everything is handwritten. https://github.com/kant2002/CoreRTWinFormsTestBed/blob/master/WinFormsComInterop/WinFormsComWrappers.cs

I have form which have almost all controls so more or less it's working. Right now most things would be in ComWrappers space and not in NativeAOT IMO. 

Code generation for ComWrappers is next thing which I will play. But this is that community can also works on.

Will try replacing FileXxxRCW, but I secretly hoping that DLlImportGenerator will reach maturity soon.

**Comment by jkotas** [comment]
DllImportGenerator won't help you with replacing the coclass RCWs.

**Comment by kant2002** [comment]
> WPF is using C++/CLI to inject code for module setup AFAIK.

@hez2010 That's bad. Anyway ball start rolling and I hope we all know how far WinForms will progress.

**Comment by kant2002** [comment]
@jkotas I take a look at runtime repository and usage of ComImport attribute,
so far only following assemblies 
- System.DirectoryServices
- System.DirectoryServices.AccountManagement
- System.Management 
- System.Speech 
Each of this assemblies has about 6-10 classes decorated. 

Does this warrant implementation of ComImport/CoClass here, or same trick as in WinForms can be used where newing of objects can be replaced with CoCreateInstanceEx?

**Comment by jkotas** [comment]
We will need an overall plan for how to make libraries like this to officially work with trimming and without BuiltInComInterop https://github.com/dotnet/runtime/issues/50500. You can start discussion in this issue about the plan, what libraries to address first, etc.

The libraries in your list are among the ones that are not very actively maintained and the test coverage is not great either, so touching them will likely raise question about how we are ensuring that the change is not regressing anything.

**Comment by kant2002** [comment]
@jkotas does @MichalStrehovsky state of work on `IDynamicInterfaceCastable` check this box ` Implement IDynamicInterfaceCastable in the Native AOT runtime`?

**Comment by jkotas** [comment]
https://github.com/dotnet/runtime/issues/72909 tracks the remaining work for `IDynamicInterfaceCastable`. I have updated the top post to reflect it.

**Comment by hez2010** [comment]
Btw what's the status of `IInspectable` now? Does it already work with current COM interop support using COM wrappers?

**Comment by jkotas** [comment]
`IInspectable` is just another user-provided interface. The runtime side of COM wrappers does not have any special handling for it. It is provided by e.g. https://github.com/microsoft/CsWinRT/search?q=IInspectable

**Comment by hez2010** [comment]
Thanks for clarification. So if I read correctly through recent related PRs, does it mean COM interop support has been finished except some edge cases in shared generics with `IDynamicInterfaceCastable` and external tools which generates COM wrappers code?

**Comment by jkotas** [comment]
Yes, modulo bugs.

**Comment by jkotas** [comment]
COM source generator proposal: https://github.com/dotnet/runtime/pull/60143

**Comment by MichalStrehovsky** [comment]
I think we can close, this was all resolved, there's even the COM source generator now.
